#GET https://osa4.onrender.com/api/blogs

#GET http://localhost:3000/api/blogs/

# POST http://localhost:3000/api/blogs
# Content-Type: application/json

# {
#   "title": "Test blog2",
#   "author": "Ile",
#   "url": "blogi2.com",
#   "likes": 2
# }

DELETE http://localhost:3000/api/blogs/

{
   "title": "Test blog"
}




#GET http://localhost:3000/api/users

# {
#     "username" : "Test",
#     "name" : "user",
#     "password" : "asd"
#   }