POST https://osa4.onrender.com/api/users
Content-Type: application/json

{
    "username" : "Test",
    "name" : "user",
    "passwordHash" : "asd"
  }

# {
#   "title": "_Id to id",
#   "author": "Ile",
#   "url": "blogi2.com",
#   "likes": 2
# }